baseURL: "https://www.kungfudev.com"
title: KungFu Developer
description:  "Welcome to Kung Fu Dev, where we believe software development requires skill, discipline, and a passion for learning. Our community of experienced developers comes together to share knowledge, collaborate on projects, and push the boundaries of what's possible with code. Join us and unleash the power of kung fu developers today!"
paginate: 5
theme: PaperMod
disqusShortname: kungfudev

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
defaultContentLanguage: en
# defaultContentLanguageInSubdir: true
googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: I'm a Kung Fu Deveveloper
    description: "My personal blog"
    keywords: [Blog, Portfolio, PaperMod]
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        # favicon16x16: "<link / abs url>"
        # favicon32x32: "<link / abs url>"
        # apple_touch_icon: "<link / abs url>"
        # safari_pinned_tab: "<link / abs url>"

    label:
        text: "KungFu Developer"
        # icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    # profileMode:
    #     enabled: false # needs to be explicitly set
    #     title: ExampleSite
    #     subtitle: "This is subtitle"
    #     imageUrl: "<img location>"
    #     imageWidth: 120
    #     imageHeight: 120
    #     imageTitle: my image
    #     buttons:
    #         - name: Posts
    #           url: posts
    #         - name: Tags
    #           url: tags

    # home-info mode
    homeInfoParams:
        Title: "I'm a Kung Fu Developer 👨🏻‍💻"
        Content: "Why **Kung Fu Developer**? Something amazing about the term **kung fu** is that it refers to any study, learning, or practice that requires patience, energy, and time to complete."

    socialIcons:
        - name: twitter
          url: "https://twitter.com/douglasmakey"
        - name: linkedin
          url: "https://www.linkedin.com/in/douglasmakey/"
        - name: github
          url: "https://github.com/douglasmakey"
        - name: discord
          url: https://discord.gg/ne7Ef5jh4w

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    # editPost:
    #     URL: "https://github.com/<path_to_repo>/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["kung fu developer", "I'm a Kung fu developer", "kung fu dev", "title", "permalink", "summary", "content"]

languages:
  en:
    contentDir: content/en
    languageName: "English"
    weight: 1
    menu:
        main:
            - identifier: search
              name: Search
              url: /search/
              weight: 1
            - identifier: tags
              name: Tags
              url: /tags/
              weight: 2
            - identifier: archives
              name: Archives
              url: /archives/
              weight: 3
  es:
    contentDir: content/es
    languageName: "Español"
    weight: 2
    menu:
      main:
          - identifier: search
            name: Busqueda
            url: /search/
            weight: 1
          - identifier: tags
            name: Etiquetas
            url: /tags/
            weight: 2
          - identifier: archives
            name: Archivos
            url: /archives/
            weight: 3
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
